# Generated by Django 3.2.13 on 2022-05-25 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('username', models.CharField(max_length=10, verbose_name='Username')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='SheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_message', models.TextField(null=True, verbose_name='s_Message')),
                ('s_file_message', models.FileField(null=True, upload_to='messages/files/<django.db.models.fields.related.ForeignKey>', verbose_name='s_File message')),
                ('s_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='s_Date and time')),
                ('s_status', models.CharField(choices=[('unreaded', 'unreaded'), ('readed', 'readed')], default='unreaded', max_length=10, verbose_name='S_Status')),
                ('s_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_owner', to='app_messenger.member', verbose_name='S_Owner')),
                ('s_recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_recepient', to='app_messenger.member', verbose_name='S_Recepient')),
            ],
            options={
                'verbose_name': 'Sheduled message',
                'verbose_name_plural': 'Sheduled messages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('file_message', models.FileField(null=True, upload_to='messages/files/<django.db.models.fields.related.ForeignKey>', verbose_name='File message')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time')),
                ('status', models.CharField(choices=[('unreaded', 'unreaded'), ('readed', 'readed')], default='unreaded', max_length=10, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app_messenger.member', verbose_name='Owner')),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to='app_messenger.member', verbose_name='Recepient')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
